name: Build and Extract live2d-widget.min.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can specify the Node.js version you want

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Upload the built `live2d-widget.min.js` file
      - name: Upload the built minified JS file
        uses: actions/upload-artifact@v3
        with:
          name: live2d-widget.min.js
          path: dist/live2d-widget.min.js
